// Build scripts cannot return Result; panicking is the only error path.
#![expect(
    clippy::expect_used,
    reason = "build scripts have no recovery path — panic is correct"
)]

//! Generate the replaceable, compile-time indexes that exactly accompany the
//! embedded Typeshed bundle. Runtime snapshots supersede these accelerators;
//! this script never chooses a Python target and never maps versions to commits.

use std::collections::BTreeSet;
use std::env;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    generate_stdlib_set(&out_dir, &manifest_dir);
    generate_stub_map(&out_dir, &manifest_dir);
}

/// Generate the baseline module-root set directly from the exact bundled ZIP.
/// Keeping no hand table or target filter here prevents the accelerator from
/// diverging from the bundle identity it describes.
fn generate_stdlib_set(out_dir: &str, manifest_dir: &Path) {
    let bundle_path = manifest_dir.join("data/typeshed/stdlib.zip");
    println!("cargo:rerun-if-changed={}", bundle_path.display());
    let modules = bundled_stdlib_roots(&bundle_path);

    let dest = Path::new(out_dir).join("stdlib_set.rs");
    let file = File::create(&dest).expect("failed to create stdlib_set.rs");
    let mut writer = BufWriter::new(file);
    write!(
        writer,
        "// Generated from data/typeshed/stdlib.zip — do not edit.\n\
         #[expect(clippy::unreadable_literal, reason = \"generated by phf_codegen\")]\n\
         /// Perfect-hash accelerator for the matching embedded Typeshed bundle.\n\
         static STDLIB_MODULES: phf::Set<&'static str> = "
    )
    .expect("write failed");

    let mut builder = phf_codegen::Set::new();
    for module in &modules {
        let _ = builder.entry(module.as_str());
    }
    let built = builder.build();
    write!(writer, "{built}").expect("write failed");
    writeln!(writer, ";").expect("write failed");
}

fn bundled_stdlib_roots(bundle_path: &Path) -> BTreeSet<String> {
    let file = File::open(bundle_path).expect("failed to open bundled stdlib ZIP");
    let mut archive = zip::ZipArchive::new(file).expect("invalid bundled stdlib ZIP");
    let mut modules = BTreeSet::new();
    for index in 0..archive.len() {
        let entry = archive
            .by_index(index)
            .expect("invalid bundled stdlib ZIP entry");
        let Some(relative) = entry.name().strip_prefix("stdlib/") else {
            continue;
        };
        if !relative.to_ascii_lowercase().ends_with(".pyi") {
            continue;
        }
        let Some(root) = relative.split('/').next() else {
            continue;
        };
        let root = root.strip_suffix(".pyi").unwrap_or(root);
        if !root.is_empty() {
            let _ = modules.insert(root.to_owned());
        }
    }
    assert!(
        !modules.is_empty(),
        "bundled stdlib ZIP contained no .pyi module roots"
    );
    modules
}

/// Generate the bundled import-root → installable stub-distribution index.
fn generate_stub_map(out_dir: &str, manifest_dir: &Path) {
    let data_path = manifest_dir.join("data/typeshed_stub_distributions.tsv");
    println!("cargo:rerun-if-changed={}", data_path.display());
    let data = fs::read_to_string(&data_path).expect("failed to read stub distribution data");

    let dest = Path::new(out_dir).join("stub_map.rs");
    let file = File::create(&dest).expect("failed to create stub_map.rs");
    let mut writer = BufWriter::new(file);
    write!(
        writer,
        "// Generated by build.rs — do not edit.\n\
         #[expect(clippy::unreadable_literal, reason = \"generated by phf_codegen\")]\n\
         /// Compile-time map from a Python import root to the typeshed stub\n\
         /// distribution that provides its types (`types-<dist>`).\n\
         static STUB_DISTRIBUTIONS: phf::Map<&'static str, &'static str> = "
    )
    .expect("write failed");

    let mut builder = phf_codegen::Map::new();
    let entries: Vec<(&str, String)> = data
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let (import_root, distribution) = line
                .split_once('\t')
                .expect("stub distribution data line must be <import_root>\\t<distribution>");
            (import_root, format!("{distribution:?}"))
        })
        .collect();
    for (import_root, distribution) in &entries {
        let _ = builder.entry(*import_root, distribution);
    }
    let built = builder.build();
    write!(writer, "{built}").expect("write failed");
    writeln!(writer, ";").expect("write failed");
}
