//! What this extension may say, and what it must no longer offer.
//!
//! The manifest assertions below are this crate's equivalent of
//! `scripts/verify-vsix-inert.sh`: the packaged artefact is a manifest plus a
//! WASM module, so the manifest is where a language server, a debug adapter, or
//! a feature command would come back.

use super::{notice_output, LABEL, NOTICE};

/// The manifest exactly as it ships — the registry reads this file.
const MANIFEST: &str = include_str!("../extension.toml");

/// The one-line copy, from [WITHDRAWAL-COPY-LINE] via the messaging spec.
const ONE_LINE: &str = "Basilisk's type checker produced incorrect results. \
Basilisk is unlisted and is being rebuilt from the ground up as a new product.";

/// Manifest lines that are TOML table headers, with whitespace trimmed.
fn tables() -> Vec<&'static str> {
    MANIFEST
        .lines()
        .map(str::trim)
        .filter(|line| line.starts_with('['))
        .collect()
}

#[test]
fn slash_command_renders_the_generated_notice_verbatim() {
    let (label, text) = notice_output();
    assert_eq!(label, LABEL);
    assert_eq!(text, NOTICE, "the panel must show the generated bytes");
}

#[test]
fn the_notice_carries_every_required_fact() {
    for required in [
        "incorrect results",
        "https://github.com/python/typing/pull/2330",
        "inert and checks nothing",
        "Remove Basilisk from your pipeline",
        "rebuilding from the ground up",
        "https://www.christianfindlay.com/blog/basilisk-conformance-apology",
    ] {
        assert!(
            NOTICE.contains(required),
            "the notice must say {required:?}"
        );
    }
}

#[test]
fn the_manifest_registers_no_language_server() {
    // A [language_servers.*] table is what made Zed launch `basilisk lsp`. The
    // binary is inert and starts no server, so advertising one would leave
    // users staring at a server that fails to start instead of the statement.
    for table in tables() {
        assert!(
            !table.starts_with("[language_servers"),
            "the extension must not register a language server: {table}"
        );
    }
}

#[test]
fn the_manifest_registers_no_debug_adapter_or_grammar() {
    for table in tables() {
        for forbidden in ["[debug_adapters", "[grammars", "[languages"] {
            assert!(
                !table.starts_with(forbidden),
                "the extension must not register {forbidden}...: {table}"
            );
        }
    }
}

#[test]
fn the_manifest_offers_exactly_one_slash_command() {
    let commands: Vec<&str> = tables()
        .into_iter()
        .filter(|table| table.starts_with("[slash_commands."))
        .collect();
    assert_eq!(
        commands,
        vec!["[slash_commands.basilisk]"],
        "the profiling, memory and test commands are gone; only the statement remains"
    );
}

#[test]
fn the_manifest_description_is_the_approved_one_line_copy() {
    assert!(
        MANIFEST.contains(&format!("description = \"{ONE_LINE}\"")),
        "the registry listing must carry the approved one-line copy"
    );
}

#[test]
fn the_extension_source_cannot_fetch_or_spawn_anything() {
    // Regression guard on the glue layer: these are the API calls that used to
    // download a release binary and hand Zed a command to run.
    let glue = include_str!("lib.rs");
    for forbidden in [
        "latest_github_release",
        "download_file",
        "make_file_executable",
        "language_server_command",
        "get_dap_binary",
    ] {
        assert!(
            !glue.contains(forbidden),
            "the extension must not call {forbidden}"
        );
    }
}
