//! Implements [LSPARCH-FEATURES]. See docs/specs/LSP-ARCHITECTURE-SPEC.md#LSPARCH-FEATURES
//!
//! Coverage XML parsing for pytest-cov Cobertura output.
//!
//! Parses `coverage.xml` (Cobertura format) generated by `pytest --cov`
//! and produces structured per-file, per-line coverage data suitable for
//! sending via the `basilisk/coverageResult` notification.

use std::path::Path;

use serde::{Deserialize, Serialize};

/// Coverage data for a single source file.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileCoverage {
    /// Relative path to the source file.
    pub file: String,
    /// Per-line coverage entries.
    pub lines: Vec<LineCoverage>,
    /// Percentage of covered lines (0.0 – 100.0).
    pub coverage_pct: f64,
}

/// Coverage data for a single line.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LineCoverage {
    /// 1-based line number.
    pub line: u32,
    /// Number of times this line was executed (0 = uncovered).
    pub hits: u32,
}

/// Aggregated coverage result for the whole workspace.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CoverageResult {
    /// Per-file coverage data.
    pub files: Vec<FileCoverage>,
    /// Overall coverage percentage (0.0 – 100.0).
    pub total_pct: f64,
}

/// Parse a Cobertura-format `coverage.xml` file.
///
/// Returns `None` if the file doesn't exist or can't be parsed.
/// Uses a simple line-based parser (no XML crate dependency) matching
/// `<class filename="...">` and `<line number="..." hits="..."/>` tags.
///
/// # Errors
///
/// Returns an error string if the file exists but can't be read.
pub fn parse_coverage_xml(path: &Path) -> Result<CoverageResult, String> {
    let content =
        std::fs::read_to_string(path).map_err(|e| format!("Failed to read coverage XML: {e}"))?;

    parse_coverage_xml_content(&content)
}

/// Parse coverage XML from a string (for testability).
///
/// # Errors
///
/// Returns an error string if the content cannot be parsed.
pub fn parse_coverage_xml_content(content: &str) -> Result<CoverageResult, String> {
    let mut files: Vec<FileCoverage> = Vec::new();
    let mut current_file: Option<String> = None;
    let mut current_lines: Vec<LineCoverage> = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Match <class filename="...">
        if let Some(filename) = extract_attr(trimmed, "filename") {
            // Flush previous file.
            if let Some(file_name) = current_file.take() {
                let coverage_pct = compute_coverage_pct(&current_lines);
                files.push(FileCoverage {
                    file: file_name,
                    lines: std::mem::take(&mut current_lines),
                    coverage_pct,
                });
            }
            current_file = Some(filename);
            continue;
        }

        // Match <line number="..." hits="..."/>
        if trimmed.starts_with("<line ") {
            if let (Some(number_str), Some(hits_str)) = (
                extract_attr(trimmed, "number"),
                extract_attr(trimmed, "hits"),
            ) {
                if let (Ok(line_num), Ok(hits)) =
                    (number_str.parse::<u32>(), hits_str.parse::<u32>())
                {
                    current_lines.push(LineCoverage {
                        line: line_num,
                        hits,
                    });
                }
            }
        }
    }

    // Flush last file.
    if let Some(file_name) = current_file.take() {
        let coverage_pct = compute_coverage_pct(&current_lines);
        files.push(FileCoverage {
            file: file_name,
            lines: current_lines,
            coverage_pct,
        });
    }

    let total_pct = compute_total_coverage(&files);

    Ok(CoverageResult { files, total_pct })
}

/// Extract an XML attribute value: `attr="value"` → `"value"`.
fn extract_attr(line: &str, attr: &str) -> Option<String> {
    let pattern = format!("{attr}=\"");
    let start = line.find(&pattern)? + pattern.len();
    let rest = line.get(start..)?;
    let end = rest.find('"')?;
    Some(rest.get(..end)?.to_owned())
}

/// Compute coverage percentage from line data.
fn compute_coverage_pct(lines: &[LineCoverage]) -> f64 {
    if lines.is_empty() {
        return 100.0;
    }
    let covered = lines.iter().filter(|l| l.hits > 0).count();
    #[expect(
        clippy::cast_precision_loss,
        clippy::as_conversions,
        reason = "line counts are small enough that f64 precision loss is irrelevant"
    )]
    let pct = (covered as f64 / lines.len() as f64) * 100.0;
    pct
}

/// Compute total coverage across all files.
fn compute_total_coverage(files: &[FileCoverage]) -> f64 {
    let total_lines: usize = files.iter().map(|f| f.lines.len()).sum();
    if total_lines == 0 {
        return 100.0;
    }
    let covered: usize = files
        .iter()
        .flat_map(|f| &f.lines)
        .filter(|l| l.hits > 0)
        .count();
    #[expect(
        clippy::cast_precision_loss,
        clippy::as_conversions,
        reason = "line counts are small enough that f64 precision loss is irrelevant"
    )]
    let pct = (covered as f64 / total_lines as f64) * 100.0;
    pct
}

#[cfg(test)]
#[expect(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::needless_raw_string_hashes,
    reason = "test-only code: expect, indexing, and raw strings acceptable in unit tests"
)]
mod tests {
    use super::*;

    #[test]
    fn parse_empty_coverage() {
        let result = parse_coverage_xml_content("").expect("should parse");
        assert!(result.files.is_empty());
        assert!((result.total_pct - 100.0).abs() < f64::EPSILON);
    }

    #[test]
    fn parse_single_file_coverage() {
        let xml = r#"<?xml version="1.0"?>
<coverage>
  <packages><package><classes>
    <class filename="src/main.py">
      <lines>
        <line number="1" hits="5"/>
        <line number="2" hits="3"/>
        <line number="3" hits="0"/>
      </lines>
    </class>
  </classes></package></packages>
</coverage>"#;

        let result = parse_coverage_xml_content(xml).expect("should parse");
        assert_eq!(result.files.len(), 1);
        assert_eq!(result.files[0].file, "src/main.py");
        assert_eq!(result.files[0].lines.len(), 3);
        assert_eq!(result.files[0].lines[0].line, 1);
        assert_eq!(result.files[0].lines[0].hits, 5);
        assert_eq!(result.files[0].lines[2].hits, 0);
        // 2/3 covered ≈ 66.67%
        assert!((result.files[0].coverage_pct - 66.666_666_666_666_67).abs() < 0.01);
    }

    #[test]
    fn parse_multiple_files() {
        let xml = r#"<coverage>
  <packages><package><classes>
    <class filename="a.py">
      <lines>
        <line number="1" hits="1"/>
        <line number="2" hits="1"/>
      </lines>
    </class>
    <class filename="b.py">
      <lines>
        <line number="1" hits="0"/>
        <line number="2" hits="0"/>
      </lines>
    </class>
  </classes></package></packages>
</coverage>"#;

        let result = parse_coverage_xml_content(xml).expect("should parse");
        assert_eq!(result.files.len(), 2);
        assert_eq!(result.files[0].file, "a.py");
        assert!((result.files[0].coverage_pct - 100.0).abs() < f64::EPSILON);
        assert_eq!(result.files[1].file, "b.py");
        assert!((result.files[1].coverage_pct).abs() < f64::EPSILON);
        // 2/4 total = 50%
        assert!((result.total_pct - 50.0).abs() < f64::EPSILON);
    }

    #[test]
    fn parse_all_covered() {
        let xml = r#"<coverage>
  <packages><package><classes>
    <class filename="perfect.py">
      <lines>
        <line number="1" hits="10"/>
        <line number="2" hits="5"/>
      </lines>
    </class>
  </classes></package></packages>
</coverage>"#;

        let result = parse_coverage_xml_content(xml).expect("should parse");
        assert!((result.total_pct - 100.0).abs() < f64::EPSILON);
    }

    #[test]
    fn parse_no_lines() {
        let xml = r#"<coverage>
  <packages><package><classes>
    <class filename="empty.py">
      <lines></lines>
    </class>
  </classes></package></packages>
</coverage>"#;

        let result = parse_coverage_xml_content(xml).expect("should parse");
        assert_eq!(result.files.len(), 1);
        assert!(result.files[0].lines.is_empty());
        assert!((result.files[0].coverage_pct - 100.0).abs() < f64::EPSILON);
    }

    #[test]
    fn extract_attr_works() {
        assert_eq!(
            extract_attr(r#"<class filename="test.py">"#, "filename"),
            Some("test.py".to_owned())
        );
        assert_eq!(
            extract_attr(r#"<line number="42" hits="3"/>"#, "number"),
            Some("42".to_owned())
        );
        assert_eq!(
            extract_attr(r#"<line number="42" hits="3"/>"#, "hits"),
            Some("3".to_owned())
        );
        assert_eq!(extract_attr(r#"<line/>"#, "number"), None);
    }

    #[test]
    fn parse_nonexistent_file() {
        let result = parse_coverage_xml(Path::new("/tmp/nonexistent_coverage_abc123.xml"));
        let _error = result.expect_err("a missing coverage file is an error, not empty coverage");
    }
}
