/**
 * HTML template for the reference graph webview.
 *
 * Generates a self-contained HTML document with inline CSS and JS that
 * renders a force-directed graph using Canvas 2D. The inline JS is
 * generated by memory-graph-script.ts. Panel management lives in
 * memory-graph.ts.
 */

import type { ReferenceGraph } from "./memory-graph";
import { buildGraphScript } from "./memory-graph-script";

// ── CSS ───────────────────────────────────────────────────────────────────

const GRAPH_CSS = `
    :root {
      --prof-mem-critical: #c084fc;
      --prof-mem-hot: #a78bfa;
      --prof-mem-leak: #f87171;
      --prof-success: #34d399;
      --prof-bg: #0a0c12;
      --prof-surface: #141820;
      --prof-border: #1a1f2e;
      --prof-text: #f0f2f7;
      --prof-text-secondary: #8892a4;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: var(--prof-bg);
      color: var(--prof-text);
      font-family: 'Space Grotesk', -apple-system, sans-serif;
      overflow: hidden;
      height: 100vh;
      display: flex;
      flex-direction: column;
    }
    .header {
      padding: 12px 16px;
      display: flex;
      align-items: center;
      gap: 12px;
      border-bottom: 1px solid var(--prof-border);
      flex-shrink: 0;
    }
    .header h1 {
      font-size: 16px;
      font-weight: 600;
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .header .accent { color: var(--prof-mem-critical); }
    .search-box {
      margin-left: auto;
      background: var(--prof-surface);
      border: 1px solid var(--prof-border);
      border-radius: 6px;
      padding: 6px 12px;
      color: var(--prof-text);
      font-size: 13px;
      width: 200px;
      outline: none;
    }
    .search-box:focus { border-color: var(--prof-mem-critical); }
    .search-box::placeholder { color: var(--prof-text-secondary); }
    .main-area { display: flex; flex: 1; overflow: hidden; }
    .canvas-container { flex: 1; position: relative; }
    canvas { display: block; width: 100%; height: 100%; }
    .sidebar {
      width: 280px;
      background: var(--prof-surface);
      border-left: 1px solid var(--prof-border);
      padding: 16px;
      overflow-y: auto;
      flex-shrink: 0;
    }
    .sidebar h2 {
      font-size: 12px;
      font-weight: 600;
      color: var(--prof-text-secondary);
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 12px;
    }
    .detail-row { margin-bottom: 10px; }
    .detail-label {
      font-size: 11px;
      color: var(--prof-text-secondary);
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    .detail-value {
      font-size: 14px;
      font-family: 'JetBrains Mono', monospace;
      margin-top: 2px;
      word-break: break-all;
    }
    .retention-path { margin-top: 16px; }
    .path-step {
      padding: 6px 8px;
      margin-bottom: 4px;
      background: var(--prof-bg);
      border-radius: 4px;
      font-size: 12px;
      font-family: 'JetBrains Mono', monospace;
    }
    .path-arrow {
      text-align: center;
      color: var(--prof-text-secondary);
      font-size: 11px;
      padding: 2px 0;
    }
    .badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 10px;
      font-size: 11px;
      font-weight: 600;
    }
    .badge-cycle {
      background: rgba(248, 113, 113, 0.2);
      color: var(--prof-mem-leak);
    }
    .badge-target {
      background: rgba(192, 132, 252, 0.2);
      color: var(--prof-mem-critical);
    }
    .tooltip {
      position: absolute;
      background: var(--prof-surface);
      border: 1px solid var(--prof-border);
      border-radius: 6px;
      padding: 8px 12px;
      font-size: 12px;
      pointer-events: none;
      opacity: 0;
      transition: opacity 100ms;
      max-width: 250px;
      z-index: 10;
    }
    .tooltip.visible { opacity: 1; }
    .tooltip .tt-type { font-weight: 600; color: var(--prof-mem-critical); }
    .tooltip .tt-size { color: var(--prof-text-secondary); margin-top: 2px; }
    .legend {
      display: flex;
      gap: 16px;
      font-size: 11px;
      color: var(--prof-text-secondary);
    }
    .legend-item { display: flex; align-items: center; gap: 4px; }
    .legend-dot { width: 8px; height: 8px; border-radius: 50%; }
    .empty-state {
      display: flex;
      align-items: center;
      justify-content: center;
      flex: 1;
      color: var(--prof-text-secondary);
      font-size: 14px;
    }`;

// ── HTML body ─────────────────────────────────────────────────────────────

const GRAPH_BODY = `
  <div class="header">
    <h1><span class="accent">BASILISK</span> REFERENCE GRAPH</h1>
    <div class="legend">
      <div class="legend-item">
        <div class="legend-dot" style="background: var(--prof-mem-critical)"></div>
        Target
      </div>
      <div class="legend-item">
        <div class="legend-dot" style="background: var(--prof-mem-hot)"></div>
        Referrer
      </div>
      <div class="legend-item">
        <div class="legend-dot" style="background: var(--prof-mem-leak)"></div>
        Cycle
      </div>
      <div class="legend-item">
        <div class="legend-dot" style="background: var(--prof-success)"></div>
        Freed
      </div>
    </div>
    <input type="text" class="search-box" id="search" placeholder="Filter by type..." />
  </div>
  <div class="main-area">
    <div class="canvas-container">
      <canvas id="graph-canvas"></canvas>
      <div class="tooltip" id="tooltip">
        <div class="tt-type" id="tt-type"></div>
        <div class="tt-size" id="tt-size"></div>
      </div>
    </div>
    <div class="sidebar" id="sidebar">
      <h2>Node Details</h2>
      <div id="sidebar-content">
        <div style="color: var(--prof-text-secondary); font-size: 13px;">
          Click a node to view details.
        </div>
      </div>
      <div class="retention-path" id="retention-path"></div>
    </div>
  </div>`;

// ── Public builder ────────────────────────────────────────────────────────

/** Build the complete HTML document for the reference graph webview. */
export function buildGraphHtml(graph: ReferenceGraph): string {
  const nodesJson = JSON.stringify(graph.nodes);
  const edgesJson = JSON.stringify(graph.edges);
  const cyclesJson = JSON.stringify(graph.cycles);
  const retentionPathJson = JSON.stringify(graph.retentionPath ?? []);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Basilisk Reference Graph</title>
  <style>${GRAPH_CSS}</style>
</head>
<body>
${GRAPH_BODY}
  <script>${buildGraphScript(nodesJson, edgesJson, cyclesJson, retentionPathJson)}</script>
</body>
</html>`;
}
