//! Implements [STUBRES-CREATE-LOCAL]. See docs/specs/CHECKER-STUB-RESOLUTION-SPEC.md#STUBRES-CREATE-LOCAL
//!
//! LSP command handler for `basilisk.stubs.createLocal`.
//!
//! Scaffolds a permissive local `.pyi` stub for an untyped package under the
//! workspace's `.basilisk/stubs/` directory — the same Tier-3 stub cache the
//! resolver auto-includes on its search path ([`basilisk_stubs::generate::cache`]).
//! Writing it there means the import resolves on the next rebuild and BSK-0152
//! clears with no config edit required.

use std::io::Write as _;
use std::path::{Path, PathBuf};

use tower_lsp::jsonrpc::Result as LspResult;
use tower_lsp::lsp_types::MessageType;
use tracing::{error, info, warn};

use super::LspServer;

/// Permissive PEP 484 stub skeleton for `module`.
///
/// **Strict by default**: the skeleton declares *nothing*, so once it exists the
/// `BSK-0152` "no stubs" error clears, and accessing any attribute the stub does
/// not declare is a `imports_module_attribute` error — forcing the developer to type what they
/// actually use. The opt-out (`def __getattr__(name: str) -> Any: ...`, the
/// authoring guide's "incomplete stub" escape hatch that makes every attribute
/// `Any`) is documented in a comment but deliberately not emitted, so the stub is
/// authoritative out of the box.
fn skeleton_for(module: &str) -> String {
    format!(
        "# Local stub for `{module}` — generated by Basilisk.\n\
         # Strict by default: declare each name you use, e.g.\n\
         #     def some_function(arg: str) -> str: ...\n\
         #     class SomeClass: ...\n\
         # Accessing an attribute this stub does not declare is a imports_module_attribute error.\n\
         # To opt out and allow ANY attribute instead, add a module-level fallback:\n\
         #     from typing import Any\n\
         #     def __getattr__(name: str) -> Any: ...\n\
         # See https://typing.python.org/en/latest/guides/writing_stubs.html\n"
    )
}

/// Whether `module` is a dotted sequence of Python identifiers.
fn is_valid_module_name(module: &str) -> bool {
    module
        .split('.')
        .all(basilisk_resolver::is_simple_python_identifier)
}

/// Write `<root>/.basilisk/stubs/<module>.pyi` with a strict skeleton.
///
/// Never clobbers an existing stub — if one is already present the developer's
/// work is preserved and `created` is `false`. Returns the path either way so
/// the caller can report where the stub lives.
fn write_local_stub(root: &Path, module: &str) -> std::io::Result<(PathBuf, bool)> {
    if !is_valid_module_name(module) {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "module must be a dotted sequence of Python identifiers",
        ));
    }

    let dir = root.join(basilisk_stubs::generate::cache::DEFAULT_CACHE_DIR);
    std::fs::create_dir_all(&dir)?;
    let stub_path = dir.join(format!("{module}.pyi"));
    let mut stub = match std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&stub_path)
    {
        Ok(stub) => stub,
        Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => {
            return Ok((stub_path, false));
        }
        Err(err) => return Err(err),
    };
    stub.write_all(skeleton_for(module).as_bytes())?;
    Ok((stub_path, true))
}

/// Resolve an existing `.pyi` and prove its target is inside a workspace root.
fn canonical_workspace_stub_path(path: &Path, roots: &[PathBuf]) -> Option<PathBuf> {
    if path.extension().is_none_or(|ext| ext != "pyi") {
        return None;
    }

    let canonical_path = path.canonicalize().ok()?;
    if !canonical_path.is_file() || canonical_path.extension().is_none_or(|ext| ext != "pyi") {
        return None;
    }

    roots
        .iter()
        .filter_map(|root| root.canonicalize().ok())
        .any(|root| canonical_path.starts_with(root))
        .then_some(canonical_path)
}

/// Handle `basilisk.stubs.createLocal` (arg: module name).
pub(super) async fn execute_create_local_stub(
    server: &LspServer,
    args: &[serde_json::Value],
) -> LspResult<Option<serde_json::Value>> {
    let Some(module) = super::uv_handlers::extract_package_arg(args) else {
        warn!("stubs.createLocal: missing module argument");
        return Ok(None);
    };
    let root = {
        let roots = server.workspace_roots.read().await;
        let Some(first) = roots.first().cloned() else {
            return Err(super::no_workspace_root_error());
        };
        first
    };

    match write_local_stub(&root, &module) {
        Ok((path, created)) => {
            let msg = if created {
                format!("Created local stub {}", path.display())
            } else {
                format!("Local stub already exists at {}", path.display())
            };
            info!(module = %module, created, "stubs.createLocal");
            server
                .client
                .log_message(MessageType::INFO, format!("Basilisk: {msg}"))
                .await;
            // Re-resolve so the new stub is picked up and BSK-0152 clears.
            super::init::rebuild_registry_and_resolve(server).await;
            Ok(Some(serde_json::json!({
                "created": created,
                "path": path.to_string_lossy(),
            })))
        }
        Err(err) => {
            error!(%err, module = %module, "stubs.createLocal failed to write stub");
            Err(tower_lsp::jsonrpc::Error {
                code: tower_lsp::jsonrpc::ErrorCode::ServerError(-32012),
                message: format!("Failed to create local stub: {err}").into(),
                data: None,
            })
        }
    }
}

/// Append `snippet` (a method/attribute declaration) to an existing stub,
/// inserting `from typing import Any` just before it when the snippet needs
/// `Any` and the stub does not already provide it.
fn append_member(content: &str, snippet: &str) -> String {
    let needs_any = snippet.contains("Any")
        && !content.contains("import Any")
        && !content.contains("import typing");
    let mut out = content.to_owned();
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    if needs_any {
        out.push_str("from typing import Any\n");
    }
    out.push_str(snippet);
    out.push('\n');
    out
}

/// Handle `basilisk.stubs.addMember` (args: stub path, snippet line).
///
/// Appends a missing method/attribute to an existing local stub so the
/// `imports_module_attribute` "no attribute" error clears, then re-resolves. Implements
/// [STUBRES-ADD-MEMBER].
pub(super) async fn execute_add_stub_member(
    server: &LspServer,
    args: &[serde_json::Value],
) -> LspResult<Option<serde_json::Value>> {
    let (Some(stub_path), Some(snippet)) = (
        args.first().and_then(serde_json::Value::as_str),
        args.get(1).and_then(serde_json::Value::as_str),
    ) else {
        warn!("stubs.addMember: missing arguments");
        return Ok(None);
    };

    // Safety: canonicalize both sides before comparing so `..` and symlinks
    // cannot redirect a lexically workspace-prefixed path outside the root.
    let path = {
        let roots = server.workspace_roots.read().await;
        canonical_workspace_stub_path(Path::new(stub_path), &roots)
    };
    let Some(path) = path else {
        warn!(
            path = stub_path,
            "stubs.addMember: not an existing workspace .pyi"
        );
        return Ok(None);
    };

    let Ok(content) = std::fs::read_to_string(&path) else {
        return Ok(None);
    };
    let updated = append_member(&content, snippet);
    if let Err(err) = std::fs::write(&path, &updated) {
        error!(%err, path = stub_path, "stubs.addMember failed to write");
        return Err(tower_lsp::jsonrpc::Error {
            code: tower_lsp::jsonrpc::ErrorCode::ServerError(-32013),
            message: format!("Failed to update stub: {err}").into(),
            data: None,
        });
    }

    info!(snippet, path = stub_path, "stubs.addMember");
    server
        .client
        .log_message(
            MessageType::INFO,
            format!("Basilisk: added `{snippet}` to {}", path.display()),
        )
        .await;
    super::init::rebuild_registry_and_resolve(server).await;
    Ok(Some(serde_json::json!({ "added": true })))
}

#[cfg(test)]
#[expect(
    clippy::unwrap_used,
    reason = "test-only code: unwrap acceptable in unit tests"
)]
mod tests {
    use super::{append_member, skeleton_for, write_local_stub};

    #[test]
    fn append_member_adds_typing_import_once() {
        let skeleton = skeleton_for("cowsay");
        let snippet = "def get_output_string(arg0: Any, arg1: Any) -> Any: ...";

        let after_first = append_member(&skeleton, snippet);
        assert!(after_first.contains("from typing import Any"));
        assert!(after_first.trim_end().ends_with(snippet));
        // The `Any` import comes before the declaration that uses it.
        assert!(
            after_first.find("from typing import Any").unwrap()
                < after_first.find(snippet).unwrap()
        );

        // A second member must not add a duplicate import.
        let after_second = append_member(&after_first, "tagline: Any");
        assert_eq!(after_second.matches("from typing import Any").count(), 1);
        assert!(after_second.trim_end().ends_with("tagline: Any"));
    }

    #[test]
    fn append_member_skips_import_when_no_any() {
        let updated = append_member("# stub\n", "def foo() -> None: ...");
        assert!(!updated.contains("from typing import Any"));
        assert!(updated.ends_with("def foo() -> None: ...\n"));
    }

    #[test]
    fn skeleton_is_strict_by_default_and_self_documenting() {
        let stub = skeleton_for("acme");
        // Strict: NO active (uncommented) declaration — every non-comment line is
        // blank, so the stub declares nothing and undeclared access is E0154.
        assert!(
            stub.lines()
                .all(|line| line.trim().is_empty() || line.trim_start().starts_with('#')),
            "the generated skeleton must declare nothing (comments only): {stub}"
        );
        assert!(stub.contains("`acme`"));
        assert!(
            stub.contains("imports_module_attribute"),
            "the skeleton must explain that undeclared access errors: {stub}"
        );
        // The opt-out is documented (as a comment), not emitted as a live def.
        assert!(stub.contains("# To opt out"));
        assert!(stub.contains("https://typing.python.org/en/latest/guides/writing_stubs.html"));
    }

    #[test]
    fn writes_stub_into_dot_basilisk_stubs() {
        let dir = tempfile::tempdir().unwrap();
        let (path, created) = write_local_stub(dir.path(), "acme_private_pkg").unwrap();
        assert!(created, "a fresh stub must report created=true");
        assert!(path.ends_with("acme_private_pkg.pyi"));
        assert!(path.is_file(), "the .pyi must exist on disk");
        let on_disk = std::fs::read_to_string(&path).unwrap();
        assert!(on_disk.contains("imports_module_attribute"));
        // It lives under the resolver's auto-included Tier-3 cache dir.
        assert!(path
            .to_string_lossy()
            .contains(basilisk_stubs::generate::cache::DEFAULT_CACHE_DIR));
    }

    #[test]
    fn does_not_clobber_existing_stub() {
        let dir = tempfile::tempdir().unwrap();
        let (path, _) = write_local_stub(dir.path(), "acme").unwrap();
        std::fs::write(&path, "# hand-written\n").unwrap();
        let (again, created) = write_local_stub(dir.path(), "acme").unwrap();
        assert!(!created, "an existing stub must not be overwritten");
        assert_eq!(again, path);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "# hand-written\n");
    }

    // [STUBRES-CREATE-LOCAL] Module names are untrusted command arguments and
    // must never become path components outside the local stub cache.
    #[test]
    fn rejects_module_names_that_escape_the_stub_cache() {
        let sandbox = tempfile::tempdir().unwrap();
        let root = sandbox.path().join("workspace");
        std::fs::create_dir(&root).unwrap();

        let result = write_local_stub(&root, "../../../escaped");

        assert!(
            result.is_err(),
            "a parent-directory module name must be rejected"
        );
        assert!(
            !sandbox.path().join("escaped.pyi").exists(),
            "an invalid module name must not write outside the workspace"
        );
    }

    #[test]
    fn rejects_invalid_dotted_module_identifiers() {
        for module in [
            "",
            "9package",
            "package..child",
            "package/child",
            "package-child",
        ] {
            let dir = tempfile::tempdir().unwrap();
            let result = write_local_stub(dir.path(), module);
            assert_eq!(
                result.as_ref().err().map(std::io::Error::kind),
                Some(std::io::ErrorKind::InvalidInput),
                "an invalid dotted module identifier must be rejected: {module:?}"
            );
        }
    }

    #[test]
    fn accepts_valid_dotted_module_names() {
        let dir = tempfile::tempdir().unwrap();
        let (path, created) = write_local_stub(dir.path(), "acme.widgets").unwrap();

        assert!(created);
        assert!(path.ends_with("acme.widgets.pyi"));
    }

    // `create_new` must treat even a dangling symlink as an occupied path;
    // checking `Path::exists` before a normal write follows it instead.
    #[cfg(unix)]
    #[test]
    fn does_not_follow_a_dangling_symlink_when_creating_a_stub() {
        let sandbox = tempfile::tempdir().unwrap();
        let root = sandbox.path().join("workspace");
        let cache = root.join(basilisk_stubs::generate::cache::DEFAULT_CACHE_DIR);
        std::fs::create_dir_all(&cache).unwrap();
        let outside = sandbox.path().join("outside.pyi");
        let stub = cache.join("acme.pyi");
        std::os::unix::fs::symlink(&outside, &stub).unwrap();

        let (path, created) = write_local_stub(&root, "acme").unwrap();

        assert_eq!(path, stub);
        assert!(!created, "an occupied stub path must not be overwritten");
        assert!(
            !outside.exists(),
            "stub creation must not follow a symlink outside the cache"
        );
    }
}
