#!/usr/bin/env python3
"""Prepare a python/typing conformance PR for Basilisk.

This script patches a python/typing checkout so the official conformance harness
runs the `basilisk` command installed from the `basilisk-python` wheel. It is
intended to leave that checkout in a submit-ready state: adapter added,
dependency added, lock file refreshed, and `results/basilisk/*.toml` generated by
the real upstream harness.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


UPSTREAM = "https://github.com/python/typing.git"
ADAPTER_PATH = (
    Path(__file__).resolve().parent.parent
    / "conformance"
    / "basilisk_conformance_adapter.py"
)
STRICT_ADAPTER_MARKER = (
    "TYPE_CHECKERS = tuple(TYPE_CHECKERS) + (BasiliskTypeChecker(),)"
)


def basilisk_adapter_source() -> str:
    try:
        return ADAPTER_PATH.read_text(encoding="utf-8").strip()
    except OSError as exc:
        raise SystemExit(
            f"cannot read Basilisk adapter source: {ADAPTER_PATH}"
        ) from exc


def run_cmd(
    cmd: list[str],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
) -> None:
    print("+", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, env=env, check=True)


def ensure_tool(name: str) -> None:
    if shutil.which(name) is None:
        raise SystemExit(f"required tool not found on PATH: {name}")


def clone_checkout(ref: str, keep_temp: bool) -> Path:
    ensure_tool("git")
    temp = Path(tempfile.mkdtemp(prefix="basilisk-typing-"))
    checkout = temp / "typing"
    run_cmd(["git", "clone", "--depth", "1", "--branch", ref, UPSTREAM, str(checkout)])
    if keep_temp:
        print(f"temporary checkout kept at {checkout}")
    return checkout


def require_typing_checkout(path: Path) -> Path:
    root = path.resolve()
    expected = root / "conformance" / "src" / "type_checker.py"
    if not expected.is_file():
        raise SystemExit(f"not a python/typing checkout: missing {expected}")
    return root


def patch_type_checker(path: Path) -> None:
    source = path.read_text(encoding="utf-8")
    if STRICT_ADAPTER_MARKER in source:
        return
    if "class BasiliskTypeChecker(TypeChecker):" in source:
        raise SystemExit(
            f"{path} already contains a Basilisk adapter; use a clean checkout "
            "or remove the stale adapter before preparing the submission"
        )
    if "TYPE_CHECKERS: Sequence[TypeChecker] = (" not in source:
        raise SystemExit(f"cannot find TYPE_CHECKERS tuple in {path}")

    adapter = basilisk_adapter_source()
    path.write_text(f"{source.rstrip()}\n\n{adapter}\n", encoding="utf-8")


def patch_pyproject(path: Path) -> None:
    source = path.read_text(encoding="utf-8")
    dependency = '    "basilisk-python",\n'
    if dependency in source:
        return
    marker = "dependencies = [\n"
    if marker not in source:
        raise SystemExit(f"cannot find dependency list in {path}")
    source = source.replace(marker, marker + dependency, 1)
    path.write_text(source, encoding="utf-8")


def install_local_wheel(conformance_dir: Path, wheel: Path) -> None:
    wheel = wheel.resolve()
    if not wheel.is_file():
        raise SystemExit(f"wheel does not exist: {wheel}")
    python = conformance_dir / ".venv" / "bin" / "python"
    if sys.platform == "win32":
        python = conformance_dir / ".venv" / "Scripts" / "python.exe"
    run_cmd(
        [
            "uv",
            "pip",
            "install",
            "--python",
            str(python),
            "--force-reinstall",
            str(wheel),
        ]
    )


def verify_basilisk_on_path(conformance_dir: Path) -> None:
    command = (
        "import shutil, subprocess; "
        "path = shutil.which('basilisk'); "
        "assert path, 'basilisk is not on PATH'; "
        "print(path); "
        "print(subprocess.check_output(['basilisk', '--version'], text=True).strip())"
    )
    run_cmd(
        ["uv", "run", "--python", "3.12", "python", "-c", command], cwd=conformance_dir
    )


def write_proof(conformance_dir: Path, output: str) -> None:
    proof = conformance_dir / "results" / "basilisk-proof.txt"
    proof.write_text(output, encoding="utf-8")
    print(f"wrote proof log: {proof}")


def run_harness(conformance_dir: Path, *, verbose: bool, write_log: bool) -> None:
    cmd = [
        "uv",
        "run",
        "--python",
        "3.12",
        "python",
        "src/main.py",
        "--only-run",
        "basilisk",
    ]
    if verbose:
        cmd.append("--verbose")
    print("+", " ".join(cmd))
    proc = subprocess.run(
        cmd,
        cwd=conformance_dir,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    print(proc.stdout, end="")
    if write_log:
        write_proof(conformance_dir, proc.stdout)
    if proc.returncode != 0:
        raise SystemExit(proc.returncode)


def prepare(args: argparse.Namespace) -> Path:
    ensure_tool("uv")
    root = (
        require_typing_checkout(args.typing_repo)
        if args.typing_repo
        else clone_checkout(args.ref, args.keep_temp)
    )
    conformance_dir = root / "conformance"

    patch_type_checker(conformance_dir / "src" / "type_checker.py")

    if args.no_run:
        patch_pyproject(conformance_dir / "pyproject.toml")
        print(f"patched python/typing checkout: {root}")
        print("run without --no-run to refresh uv.lock and generate results/basilisk")
        return root

    if args.wheel:
        # Pre-PyPI proof: keep pyproject unchanged until the local wheel is
        # installed, otherwise uv sync would try to resolve basilisk-python from
        # the public index before it exists. The submit-ready dependency line is
        # still added after the harness has run.
        run_cmd(["uv", "sync", "--python", "3.12"], cwd=conformance_dir)
        install_local_wheel(conformance_dir, args.wheel)
    else:
        patch_pyproject(conformance_dir / "pyproject.toml")
        run_cmd(["uv", "sync", "--python", "3.12"], cwd=conformance_dir)

    verify_basilisk_on_path(conformance_dir)
    run_harness(conformance_dir, verbose=args.verbose, write_log=args.write_proof)
    run_cmd(
        ["uv", "run", "--python", "3.12", "python", "src/main.py", "--report-only"],
        cwd=conformance_dir,
    )
    if args.wheel:
        patch_pyproject(conformance_dir / "pyproject.toml")
        print(
            "local wheel proof complete; rerun without --wheel after PyPI publish "
            "to refresh uv.lock with the public basilisk-python dependency"
        )

    print()
    print("python/typing checkout is ready for review:")
    print(f"  {root}")
    print("Expected PR files include:")
    print("  conformance/pyproject.toml")
    print("  conformance/uv.lock")
    print("  conformance/src/type_checker.py")
    print("  conformance/results/basilisk/*.toml")
    print("  conformance/results/results.html")
    return root


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Patch python/typing so Basilisk can be submitted to the conformance suite."
    )
    parser.add_argument(
        "--typing-repo",
        type=Path,
        help="Existing python/typing checkout to patch. Defaults to a fresh temp clone.",
    )
    parser.add_argument(
        "--ref",
        default="main",
        help="python/typing ref to clone when --typing-repo is omitted.",
    )
    parser.add_argument(
        "--wheel",
        type=Path,
        help="Local basilisk-python wheel to force-install after uv sync. Omit to use PyPI.",
    )
    parser.add_argument(
        "--no-run",
        action="store_true",
        help="Patch files only; do not run uv or the harness.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Pass --verbose to upstream conformance harness.",
    )
    parser.add_argument(
        "--write-proof",
        action="store_true",
        help="Write harness output to results/basilisk-proof.txt.",
    )
    parser.add_argument(
        "--keep-temp", action="store_true", help="Print and keep the temp clone path."
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    prepare(parse_args(argv))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
