//! Bundled type stubs and stdlib module index for Basilisk.
//!
//! Provides:
//! - O(1) stdlib module recognition via a compile-time `phf` hash set
//! - Built-in type lookup for Python primitives
//! - Stub resolution data model ([`StubResolution`], [`StubSource`], [`StubTier`])

pub mod generate;
pub mod pyi_parser;
pub mod types;

pub use pyi_parser::{parse_pyi_file, parse_pyi_source, StubParseError};
pub use types::{
    StubClass, StubFunction, StubModule, StubParam, StubParamKind, StubResolution, StubSource,
    StubTier, StubVariable, TypeProvenance,
};

// Generated by `build.rs` — contains `static STDLIB_MODULES: phf::Set<&'static str>`.
include!(concat!(env!("OUT_DIR"), "/stdlib_set.rs"));

/// Check whether a top-level module name belongs to the `CPython` 3.12 stdlib.
///
/// Extracts the root segment (before the first `.`) and checks it against the
/// compiled typeshed index. O(1) lookup via perfect hashing.
#[must_use]
pub fn is_stdlib_module(module_name: &str) -> bool {
    let root = module_name.split('.').next().unwrap_or(module_name);
    STDLIB_MODULES.contains(root)
}

/// Look up the type annotation string for a built-in symbol.
///
/// Returns type information for Python built-in types.
/// Unknown names return `None`.
#[must_use]
pub fn lookup_builtin(name: &str) -> Option<&'static str> {
    match name {
        "int" => Some("int"),
        "float" => Some("float"),
        "str" => Some("str"),
        "bytes" => Some("bytes"),
        "bool" => Some("bool"),
        "list" => Some("list"),
        "dict" => Some("dict"),
        "set" => Some("set"),
        "tuple" => Some("tuple"),
        "frozenset" => Some("frozenset"),
        "type" => Some("type"),
        "object" => Some("object"),
        "None" => Some("None"),
        "complex" => Some("complex"),
        "range" => Some("range"),
        "bytearray" => Some("bytearray"),
        "memoryview" => Some("memoryview"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stdlib_known_modules_detected() {
        assert!(is_stdlib_module("os"));
        assert!(is_stdlib_module("sys"));
        assert!(is_stdlib_module("typing"));
        assert!(is_stdlib_module("collections"));
        assert!(is_stdlib_module("asyncio"));
        assert!(is_stdlib_module("json"));
        assert!(is_stdlib_module("pathlib"));
        assert!(is_stdlib_module("dataclasses"));
        assert!(is_stdlib_module("functools"));
        assert!(is_stdlib_module("itertools"));
        assert!(is_stdlib_module("__future__"));
        assert!(is_stdlib_module("typing_extensions"));
        assert!(is_stdlib_module("tomllib"));
        assert!(is_stdlib_module("zoneinfo"));
        assert!(is_stdlib_module("graphlib"));
    }

    #[test]
    fn stdlib_dotted_names_resolved() {
        assert!(is_stdlib_module("os.path"));
        assert!(is_stdlib_module("collections.abc"));
        assert!(is_stdlib_module("typing.io"));
        assert!(is_stdlib_module("http.server"));
        assert!(is_stdlib_module("email.mime.text"));
        assert!(is_stdlib_module("concurrent.futures"));
    }

    #[test]
    fn third_party_not_in_stdlib() {
        assert!(!is_stdlib_module("requests"));
        assert!(!is_stdlib_module("flask"));
        assert!(!is_stdlib_module("django"));
        assert!(!is_stdlib_module("numpy"));
        assert!(!is_stdlib_module("pandas"));
        assert!(!is_stdlib_module("fastmcp"));
        assert!(!is_stdlib_module("pydantic"));
    }

    #[test]
    fn empty_module_not_stdlib() {
        assert!(!is_stdlib_module(""));
    }

    #[test]
    fn builtin_lookup_works() {
        assert_eq!(lookup_builtin("int"), Some("int"));
        assert_eq!(lookup_builtin("str"), Some("str"));
        assert_eq!(lookup_builtin("None"), Some("None"));
        assert_eq!(lookup_builtin("unknown"), None);
    }

    #[test]
    fn stub_types_constructible() {
        let resolution = StubResolution {
            module: "os".to_owned(),
            source: StubSource::Typeshed,
            pyi_path: None,
            tier: StubTier::Tier1,
        };
        assert_eq!(resolution.source, StubSource::Typeshed);
        assert_eq!(resolution.tier, StubTier::Tier1);
    }

    #[test]
    fn stub_tier_ordering() {
        assert!(StubTier::Tier1 < StubTier::Tier2);
        assert!(StubTier::Tier2 < StubTier::Tier3);
    }

    #[test]
    fn internal_modules_recognized() {
        assert!(is_stdlib_module("_thread"));
        assert!(is_stdlib_module("_io"));
        assert!(is_stdlib_module("_collections_abc"));
    }

    #[test]
    fn basilisk_always_typed() {
        assert!(is_stdlib_module("basilisk"));
        assert!(is_stdlib_module("basilisk.types"));
    }

    #[test]
    fn type_provenance_from_stub_source_and_tier() {
        use types::{StubSource, StubTier, TypeProvenance};

        assert_eq!(
            TypeProvenance::from((&StubSource::Typeshed, &StubTier::Tier1)),
            TypeProvenance::StubTier1
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::StubPackage, &StubTier::Tier1)),
            TypeProvenance::StubTier1
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::UserStub, &StubTier::Tier2)),
            TypeProvenance::StubTier2
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::InlineTyped, &StubTier::Tier3)),
            TypeProvenance::StubTier3
        );
    }

    #[test]
    fn type_provenance_hover_labels() {
        use types::TypeProvenance;

        assert_eq!(TypeProvenance::Source.hover_label(), None);
        assert!(TypeProvenance::StubTier1
            .hover_label()
            .unwrap()
            .contains("typeshed"));
        assert!(TypeProvenance::Untyped
            .hover_label()
            .unwrap()
            .contains("no type stubs"));
    }
}
