//! Implements [STUBRES-ENGINE]. See docs/specs/CHECKER-STUB-RESOLUTION-SPEC.md#STUBRES-ENGINE
//! Standard-library typeshed resolution for Basilisk: the runtime
//! `python/typeshed` clone/cache is canonical; the compiled data below is the
//! offline day-one baseline it overrides ([STUBRES-TYPESHED-BASELINE]).
//!
//! Provides:
//! - O(1) stdlib module-name recognition over the offline baseline (a `phf`
//!   set), superseded at runtime by the cloned typeshed's `stdlib/VERSIONS`
//! - Built-in type lookup for Python primitives
//! - Stub resolution data model ([`StubResolution`], [`StubSource`], [`StubTier`])

pub mod builtin_members;
pub mod generate;
pub mod pyi_parser;
pub mod reexports;
pub mod types;

pub use builtin_members::builtin_method_signature;
pub use pyi_parser::{parse_pyi_file, parse_pyi_source, StubParseError};
pub use reexports::reexported_member_names;
pub use types::{
    StarReexport, StubClass, StubFunction, StubModule, StubParam, StubParamKind, StubResolution,
    StubSource, StubTier, StubVariable, TypeProvenance,
};

// Generated by `build.rs` — the offline baseline stdlib name-set
// (`static STDLIB_MODULES: phf::Set<&'static str>`), overridden at runtime by
// the cloned typeshed's `stdlib/VERSIONS` ([STUBRES-TYPESHED-BASELINE]).
include!(concat!(env!("OUT_DIR"), "/stdlib_set.rs"));

// Generated by `build.rs` — the offline baseline `types-<dist>` map
// (`static STUB_DISTRIBUTIONS: phf::Map<&'static str, &'static str>`),
// overridden at runtime by the cloned typeshed's `stubs/<DIST>/` tree.
include!(concat!(env!("OUT_DIR"), "/stub_map.rs"));

/// Check whether a top-level module name belongs to the `CPython` 3.12 stdlib.
///
/// Extracts the root segment (before the first `.`) and checks it against the
/// offline baseline name-set. O(1) lookup via perfect hashing.
// Implements [STUBRES-TYPESHED] — this set is the offline baseline built by
// `build.rs` into a `phf` set for O(1) lookup; the runtime clone's
// `stdlib/VERSIONS` supersedes it. The stdlib list is derived data, not a
// maintained list.
#[must_use]
pub fn is_stdlib_module(module_name: &str) -> bool {
    let root = module_name.split('.').next().unwrap_or(module_name);
    STDLIB_MODULES.contains(root)
}

/// Look up the typeshed stub distribution (`types-<dist>`) that provides types
/// for a given import.
///
/// Extracts the root segment (before the first `.`) and checks it against the
/// `types-<dist>` map (the runtime clone's `stubs/<DIST>/` tree, or the offline
/// baseline when no clone is available). Returns the `PyPI` distribution name
/// installable via `uv add --dev` (e.g. `requests` → `types-requests`, `yaml` →
/// `types-PyYAML`). Returns `None` when no typeshed stub distribution is known —
/// either the package ships inline `py.typed` types or no stubs exist — so
/// callers can avoid suggesting a package that would fail to resolve on `PyPI`.
// Implements [STUBRES-PEP561] step 3 (stub-only packages) — names the
// `types-<dist>` distribution the resolver/quick-fix installs to satisfy a
// stub-only import; backed by the `build.rs`-generated typeshed stub map.
#[must_use]
pub fn typeshed_stub_distribution(module_name: &str) -> Option<&'static str> {
    let root = module_name.split('.').next().unwrap_or(module_name);
    STUB_DISTRIBUTIONS.get(root).copied()
}

/// Whether the package containing `resolved_path` ships a PEP 561 `py.typed`
/// marker (i.e. opts in to inline type distribution).
///
/// Walks up from the resolved file looking for a `py.typed` file, stopping at
/// the `site-packages` boundary — installed packages are its direct children,
/// so the marker never lives at or above that level. Implements [STUBRES-ENGINE].
// Implements [STUBRES-PEP561] step 4 (inline-typed packages) — detects the
// PEP 561 `py.typed` opt-in marker that distinguishes an inline-typed package
// from an untyped one.
#[must_use]
pub fn has_py_typed_marker(resolved_path: &std::path::Path) -> bool {
    let mut dir = resolved_path.parent();
    while let Some(current) = dir {
        if current.file_name() == Some(std::ffi::OsStr::new("site-packages")) {
            return false;
        }
        if current.join("py.typed").is_file() {
            return true;
        }
        dir = current.parent();
    }
    false
}

/// Look up the type annotation string for a built-in symbol.
///
/// Returns type information for Python built-in types.
/// Unknown names return `None`.
// Implements [STUBRES-TYPESHED] — `lookup_builtin()` over Python primitives
// (part of the typeshed-backed standard-library surface).
#[must_use]
pub fn lookup_builtin(name: &str) -> Option<&'static str> {
    match name {
        "int" => Some("int"),
        "float" => Some("float"),
        "str" => Some("str"),
        "bytes" => Some("bytes"),
        "bool" => Some("bool"),
        "list" => Some("list"),
        "dict" => Some("dict"),
        "set" => Some("set"),
        "tuple" => Some("tuple"),
        "frozenset" => Some("frozenset"),
        "type" => Some("type"),
        "object" => Some("object"),
        "None" => Some("None"),
        "complex" => Some("complex"),
        "range" => Some("range"),
        "bytearray" => Some("bytearray"),
        "memoryview" => Some("memoryview"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stdlib_known_modules_detected() {
        assert!(is_stdlib_module("os"));
        assert!(is_stdlib_module("sys"));
        assert!(is_stdlib_module("typing"));
        assert!(is_stdlib_module("collections"));
        assert!(is_stdlib_module("asyncio"));
        assert!(is_stdlib_module("json"));
        assert!(is_stdlib_module("pathlib"));
        assert!(is_stdlib_module("dataclasses"));
        assert!(is_stdlib_module("functools"));
        assert!(is_stdlib_module("itertools"));
        assert!(is_stdlib_module("__future__"));
        assert!(is_stdlib_module("typing_extensions"));
        assert!(is_stdlib_module("tomllib"));
        assert!(is_stdlib_module("zoneinfo"));
        assert!(is_stdlib_module("graphlib"));
    }

    #[test]
    fn stdlib_dotted_names_resolved() {
        assert!(is_stdlib_module("os.path"));
        assert!(is_stdlib_module("collections.abc"));
        assert!(is_stdlib_module("typing.io"));
        assert!(is_stdlib_module("http.server"));
        assert!(is_stdlib_module("email.mime.text"));
        assert!(is_stdlib_module("concurrent.futures"));
    }

    #[test]
    fn third_party_not_in_stdlib() {
        assert!(!is_stdlib_module("requests"));
        assert!(!is_stdlib_module("flask"));
        assert!(!is_stdlib_module("django"));
        assert!(!is_stdlib_module("numpy"));
        assert!(!is_stdlib_module("pandas"));
        assert!(!is_stdlib_module("fastmcp"));
        assert!(!is_stdlib_module("pydantic"));
    }

    #[test]
    fn empty_module_not_stdlib() {
        assert!(!is_stdlib_module(""));
    }

    #[test]
    fn builtin_lookup_works() {
        assert_eq!(lookup_builtin("int"), Some("int"));
        assert_eq!(lookup_builtin("str"), Some("str"));
        assert_eq!(lookup_builtin("None"), Some("None"));
        assert_eq!(lookup_builtin("unknown"), None);
    }

    #[test]
    fn stub_types_constructible() {
        let resolution = StubResolution {
            module: "os".to_owned(),
            source: StubSource::Typeshed,
            pyi_path: None,
            tier: StubTier::Tier1,
        };
        assert_eq!(resolution.source, StubSource::Typeshed);
        assert_eq!(resolution.tier, StubTier::Tier1);
    }

    #[test]
    fn stub_tier_ordering() {
        assert!(StubTier::Tier1 < StubTier::Tier2);
        assert!(StubTier::Tier2 < StubTier::Tier3);
    }

    #[test]
    fn internal_modules_recognized() {
        assert!(is_stdlib_module("_thread"));
        assert!(is_stdlib_module("_io"));
        assert!(is_stdlib_module("_collections_abc"));
    }

    #[test]
    fn basilisk_always_typed() {
        assert!(is_stdlib_module("basilisk"));
        assert!(is_stdlib_module("basilisk.types"));
    }

    #[test]
    fn type_provenance_from_stub_source_and_tier() {
        use types::{StubSource, StubTier, TypeProvenance};

        assert_eq!(
            TypeProvenance::from((&StubSource::Typeshed, &StubTier::Tier1)),
            TypeProvenance::StubTier1
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::StubPackage, &StubTier::Tier1)),
            TypeProvenance::StubTier1
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::UserStub, &StubTier::Tier2)),
            TypeProvenance::StubTier2
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::InlineTyped, &StubTier::Tier3)),
            TypeProvenance::StubTier3
        );
        // A custom typeshed (`typeshed-path`) keeps Tier-1 trust but its OWN
        // provenance so hover can distinguish it from the default typeshed
        // (runtime clone or offline baseline) ([STUBRES-CUSTOM-TYPESHED]). Only
        // the `(CustomTypeshed,
        // Tier1)` pair special-cases — every other tier for the same source falls
        // through to the generic tier mapping, never to `StubCustomTypeshed`.
        assert_eq!(
            TypeProvenance::from((&StubSource::CustomTypeshed, &StubTier::Tier1)),
            TypeProvenance::StubCustomTypeshed,
            "a custom-typeshed Tier-1 stub must map to StubCustomTypeshed"
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::CustomTypeshed, &StubTier::Tier2)),
            TypeProvenance::StubTier2,
            "only Tier1 special-cases custom typeshed; Tier2 stays StubTier2"
        );
        assert_eq!(
            TypeProvenance::from((&StubSource::CustomTypeshed, &StubTier::Tier3)),
            TypeProvenance::StubTier3,
            "only Tier1 special-cases custom typeshed; Tier3 stays StubTier3"
        );
    }

    #[test]
    fn type_provenance_hover_labels() {
        use types::TypeProvenance;

        // Exact labels — every provenance renders a distinct suffix, so a mutant
        // that swaps a match arm or edits a string is caught. `(custom typeshed)`
        // is deliberately distinct from `(typeshed)` so a MicroPython signature is
        // never misreported as the bundled CPython one ([STUBRES-CUSTOM-TYPESHED]).
        assert_eq!(TypeProvenance::Source.hover_label(), None);
        assert_eq!(TypeProvenance::StubTier1.hover_label(), Some("(typeshed)"));
        assert_eq!(
            TypeProvenance::StubCustomTypeshed.hover_label(),
            Some("(custom typeshed)")
        );
        assert_eq!(
            TypeProvenance::StubTier2.hover_label(),
            Some("(community stub)")
        );
        assert_eq!(
            TypeProvenance::StubTier3.hover_label(),
            Some("(best-effort stub, may be inaccurate)")
        );
        assert_eq!(
            TypeProvenance::Untyped.hover_label(),
            Some("(no type stubs available)")
        );
        // `(custom typeshed)` must NOT be confused with the bundled `(typeshed)`:
        // the two labels are different strings even though one contains the other.
        assert_ne!(
            TypeProvenance::StubCustomTypeshed.hover_label(),
            TypeProvenance::StubTier1.hover_label()
        );
    }
}
