//! Stub resolution data model.
//!
//! These types represent how a module's type information was discovered
//! and its quality tier. Used by the import resolver and type checker
//! to determine diagnostic behaviour and hover display.

use std::path::PathBuf;

/// Result of resolving type stubs for a module.
#[derive(Debug, Clone)]
pub struct StubResolution {
    /// The dotted module name that was resolved.
    pub module: String,
    /// Where the stub came from.
    pub source: StubSource,
    /// Filesystem path to the `.pyi` stub file, if one exists.
    pub pyi_path: Option<PathBuf>,
    /// Quality tier of the type information.
    pub tier: StubTier,
}

/// Where a module's type information originated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StubSource {
    /// User-provided `.pyi` files from `stub-paths` config directories.
    UserStub,
    /// Installed `foopkg-stubs` package (e.g. `types-requests`).
    StubPackage,
    /// Installed package with `py.typed` marker (PEP 561 inline types).
    InlineTyped,
    /// Bundled typeshed (compiled into the binary).
    Typeshed,
}

/// Quality tier of type information.
///
/// Determines diagnostic severity for downstream type errors and
/// the annotation shown in LSP hover tooltips.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum StubTier {
    /// Hand-written, verified stubs (typeshed, official `-stubs` packages).
    Tier1,
    /// Auto-generated, community-reviewed stubs.
    Tier2,
    /// Best-effort inference (auto-generated by `basilisk stubs generate`).
    Tier3,
}
