//! Implements [STUBRES-ENGINE]. See docs/specs/CHECKER-STUB-RESOLUTION-SPEC.md#STUBRES-ENGINE
//! Stub resolution data model.
//!
//! These types represent how a module's type information was discovered
//! and its quality tier. Used by the import resolver and type checker
//! to determine diagnostic behaviour and hover display.
//!
//! Also contains [`StubModule`] and related types for representing
//! extracted type information from `.pyi` stub files.

use std::collections::HashMap;
use std::path::PathBuf;

/// Result of resolving type stubs for a module.
#[derive(Debug, Clone)]
pub struct StubResolution {
    /// The dotted module name that was resolved.
    pub module: String,
    /// Where the stub came from.
    pub source: StubSource,
    /// Filesystem path to the `.pyi` stub file, if one exists.
    pub pyi_path: Option<PathBuf>,
    /// Quality tier of the type information.
    pub tier: StubTier,
}

/// Where a module's type information originated.
///
/// Source of truth: the typeDiagram model [`models/stub_resolution.td`] →
/// [`docs/models/stub_resolution.svg`]; keep the two in lockstep
/// (`typediagram --to rust models/stub_resolution.td`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StubSource {
    /// User-provided `.pyi` files from `stub-paths` config directories
    /// (typing-spec import-resolution step 1).
    UserStub,
    /// Installed `foopkg-stubs` package, e.g. `types-requests`
    /// (typing-spec import-resolution step 4).
    StubPackage,
    /// Installed package with `py.typed` marker, PEP 561 inline types
    /// (typing-spec import-resolution step 5).
    InlineTyped,
    /// Bundled typeshed (compiled into the binary) — typing-spec
    /// import-resolution step 3, the vendored default.
    Typeshed,
    /// Custom/modified typeshed from the `typeshed-path` config — typing-spec
    /// import-resolution **step 3 override**, *the canonical source for
    /// standard-library types* when configured. Requested in
    /// [issue #271](https://github.com/Nimblesite/Basilisk/issues/271); the
    /// distinct provenance keeps hover honest (e.g. a MicroPython `os.uname`
    /// is never misreported as the bundled CPython signature).
    /// See [STUBRES-CUSTOM-TYPESHED].
    CustomTypeshed,
}

/// Quality tier of type information.
///
/// Determines diagnostic severity for downstream type errors and
/// the annotation shown in LSP hover tooltips.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum StubTier {
    /// Hand-written, verified stubs (typeshed, official `-stubs` packages).
    Tier1,
    /// Auto-generated, community-reviewed stubs.
    Tier2,
    /// Best-effort inference (auto-generated by `basilisk stubs generate`).
    Tier3,
}

/// Where a type's information originated, from the perspective of the type
/// checker.  Used for cascade suppression (suppress downstream errors from
/// untyped imports) and hover annotations.
// Implements [STUBRES-PROVENANCE] — the `TypeProvenance` metadata each tracked
// type carries; cascade-suppression behaviour by variant lives in the checker
// (out of crate; see report).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum TypeProvenance {
    /// From source code annotations or inference.
    Source,
    /// From typeshed or hand-written, verified stubs.
    StubTier1,
    /// From a custom/modified typeshed (`typeshed-path`, issue #271) — Tier-1
    /// trust, but distinct provenance so hover reads `(custom typeshed)` and a
    /// MicroPython signature is never misreported as the bundled CPython one.
    /// See [STUBRES-CUSTOM-TYPESHED].
    StubCustomTypeshed,
    /// From auto-generated, community-reviewed stubs.
    StubTier2,
    /// From best-effort auto-generated stubs (`basilisk stubs generate`).
    StubTier3,
    /// No type information available — import is unresolved.
    Untyped,
}

impl From<(&StubSource, &StubTier)> for TypeProvenance {
    fn from((source, tier): (&StubSource, &StubTier)) -> Self {
        match (source, tier) {
            // A custom typeshed keeps Tier-1 trust but its own provenance, so
            // hover can distinguish it from the bundled typeshed ([#271]).
            (&StubSource::CustomTypeshed, &StubTier::Tier1) => Self::StubCustomTypeshed,
            (_, &StubTier::Tier1) => Self::StubTier1,
            (_, &StubTier::Tier2) => Self::StubTier2,
            (_, &StubTier::Tier3) => Self::StubTier3,
        }
    }
}

impl TypeProvenance {
    /// Human-readable label for hover tooltips.
    // Implements [STUBRES-PROVENANCE-HOVER] — the per-provenance suffix shown in
    // LSP hover (e.g. `(typeshed)`, `(best-effort stub, may be inaccurate)`,
    // `(no type stubs available)`); the LSP hover renderer appends it.
    #[must_use]
    pub fn hover_label(self) -> Option<&'static str> {
        match self {
            Self::Source => None,
            Self::StubTier1 => Some("(typeshed)"),
            Self::StubCustomTypeshed => Some("(custom typeshed)"),
            Self::StubTier2 => Some("(community stub)"),
            Self::StubTier3 => Some("(best-effort stub, may be inaccurate)"),
            Self::Untyped => Some("(no type stubs available)"),
        }
    }
}

// ---------------------------------------------------------------------------
// Parsed stub types — extracted from `.pyi` files
// ---------------------------------------------------------------------------

/// A single parameter in a stub function signature.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubParam {
    /// Parameter name.
    pub name: String,
    /// Type annotation text (e.g. `"int"`, `"str | None"`).
    pub annotation: Option<String>,
    /// Whether the parameter has a default value.
    pub has_default: bool,
    /// Parameter kind.
    pub kind: StubParamKind,
}

/// How a parameter is passed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StubParamKind {
    /// Normal positional-or-keyword parameter.
    Regular,
    /// `*args` variadic positional.
    Vararg,
    /// `**kwargs` variadic keyword.
    Kwarg,
    /// Keyword-only (appears after `*`).
    KeywordOnly,
    /// Positional-only (appears before `/`).
    PositionalOnly,
}

/// A single function signature extracted from a `.pyi` file.
///
/// When `@overload` is used, each overload is a separate `StubFunction`.
/// The overload group is tracked in [`StubModule::overloads`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubFunction {
    /// Function name.
    pub name: String,
    /// Parameters (excluding `self`/`cls`).
    pub params: Vec<StubParam>,
    /// Return type annotation text.
    pub return_type: Option<String>,
    /// Whether this signature is an `@overload` variant.
    pub is_overload: bool,
    /// Whether this is an `async def`.
    pub is_async: bool,
    /// Decorator names (e.g. `"staticmethod"`, `"classmethod"`).
    pub decorators: Vec<String>,
    /// Containing class name, if this is a method.
    pub class_name: Option<String>,
}

/// A class definition extracted from a `.pyi` file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubClass {
    /// Class name.
    pub name: String,
    /// Base class names (text form).
    pub bases: Vec<String>,
    /// Methods defined on this class.
    pub methods: Vec<StubFunction>,
    /// Class-level variable annotations (e.g. `x: int`).
    pub attributes: Vec<StubVariable>,
}

/// A module-level or class-level variable annotation from a `.pyi` file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubVariable {
    /// Variable name.
    pub name: String,
    /// Type annotation text.
    pub annotation: Option<String>,
}

/// All type information extracted from a single `.pyi` file.
///
/// Designed for efficient lookup by symbol name. Overloaded functions
/// are grouped together — [`overloads`](StubModule::overloads) maps a
/// function name to all its `@overload` variants.
#[derive(Debug, Clone)]
pub struct StubModule {
    /// The dotted module name (e.g. `"os.path"`).
    pub module_name: String,
    /// Filesystem path to the `.pyi` file.
    pub path: PathBuf,
    /// Where this stub came from (user stubs, stub package, typeshed, …).
    pub source: StubSource,
    /// Quality tier of the type information.
    pub tier: StubTier,
    /// Top-level function stubs (non-overloaded or the implementation signature).
    pub functions: HashMap<String, StubFunction>,
    /// Overload groups: function name → ordered list of `@overload` variants.
    pub overloads: HashMap<String, Vec<StubFunction>>,
    /// Class definitions.
    pub classes: HashMap<String, StubClass>,
    /// Module-level variable annotations.
    pub variables: HashMap<String, StubVariable>,
}
