//! Implements [STUBRES-TYPE-MODEL] and [STUBRES-ENGINE]. See
//! docs/specs/CHECKER-STUB-RESOLUTION-SPEC.md#STUBRES-TYPE-MODEL
//! Stub resolution data model.
//!
//! These types represent how a module's type information was discovered
//! and its quality tier. Used by the import resolver and type checker
//! to determine diagnostic behaviour and hover display.
//!
//! Also contains [`StubModule`] and related types for representing
//! extracted type information from `.pyi` stub files.

use std::collections::HashMap;
use std::path::PathBuf;

/// Result of resolving type stubs for a module.
#[derive(Debug, Clone)]
pub struct StubResolution {
    /// The dotted module name that was resolved.
    pub module: String,
    /// Where the stub came from.
    pub source: StubSource,
    /// Filesystem path to the `.pyi` stub file, if one exists.
    pub pyi_path: Option<PathBuf>,
    /// Quality tier of the type information.
    pub tier: StubTier,
}

/// Where a module's type information originated.
///
/// Source of truth: the typeDiagram model [`models/stub_resolution.td`] →
/// [`docs/models/stub_resolution.svg`]; keep the two in lockstep
/// (`typediagram --to rust models/stub_resolution.td`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StubSource {
    /// User-provided `.pyi` files from `stub-paths` config directories
    /// (typing-spec import-resolution step 1).
    UserStub,
    /// Installed `foopkg-stubs` package, e.g. `types-requests`
    /// (typing-spec import-resolution step 4).
    StubPackage,
    /// Installed package with `py.typed` marker, PEP 561 inline types
    /// (typing-spec import-resolution step 5).
    InlineTyped,
    /// Typeshed resolved from a runtime `python/typeshed` archive, or from the
    /// bundled offline snapshot when download is unavailable — typing-spec
    /// import-resolution step 3, the default standard-library source. See
    /// [STUBRES-TYPESHED].
    Typeshed,
    /// Custom/modified typeshed from the `typeshed-path` config — typing-spec
    /// import-resolution **step 3 override**, *the canonical source for
    /// standard-library types* when configured. The distinct provenance keeps
    /// hover honest (e.g. a `MicroPython` `os.uname` is never misreported as the
    /// bundled `CPython` signature). See [STUBRES-CUSTOM-TYPESHED].
    CustomTypeshed,
}

/// Quality tier of type information.
///
/// Determines diagnostic severity for downstream type errors and
/// the annotation shown in LSP hover tooltips.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum StubTier {
    /// Hand-written, verified stubs (typeshed, official `-stubs` packages).
    Tier1,
    /// Auto-generated, community-reviewed stubs.
    Tier2,
    /// Best-effort inference (auto-generated by `basilisk stubs generate`).
    Tier3,
}

/// Stable prefix written as the first line of every `basilisk stubs generate`
/// result. Removing it deliberately promotes the file to a user-maintained
/// step-1 stub; adding it deliberately marks the file best-effort.
pub const GENERATED_STUB_HEADER_PREFIX: &str = "# Auto-generated stub for `";

/// Classify user-stub source without relying on its path. This keeps disk and
/// unsaved-buffer parsing identical and lets create-local files in the same
/// `.basilisk/stubs` directory remain trusted user stubs.
#[must_use]
pub fn user_stub_tier(source_text: &str) -> StubTier {
    if source_text
        .lines()
        .next()
        .is_some_and(|line| line.starts_with(GENERATED_STUB_HEADER_PREFIX))
    {
        StubTier::Tier3
    } else {
        StubTier::Tier1
    }
}

/// Where a type's information originated, from the perspective of the type
/// checker.  Used for cascade suppression (suppress downstream errors from
/// untyped imports) and hover annotations.
// Implements [STUBRES-PROVENANCE] — the `TypeProvenance` metadata each tracked
// type carries; cascade-suppression behaviour by variant lives in the checker
// (out of crate; see report).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum TypeProvenance {
    /// From source code annotations or inference.
    Source,
    /// From typeshed or hand-written, verified stubs.
    StubTier1,
    /// From a user-authored step-1 stub. It is trusted but not labelled as
    /// typeshed in hover.
    StubUser,
    /// From a custom/modified typeshed (`typeshed-path`) — Tier-1 trust, but
    /// distinct provenance so hover reads `(custom typeshed)` and a `MicroPython`
    /// signature is never misreported as the default `CPython` one (resolved from
    /// the selected archive or bundled snapshot).
    /// See [STUBRES-CUSTOM-TYPESHED].
    StubCustomTypeshed,
    /// From auto-generated, community-reviewed stubs.
    StubTier2,
    /// From best-effort auto-generated stubs (`basilisk stubs generate`).
    StubTier3,
    /// No type information available — import is unresolved.
    Untyped,
}

impl From<(&StubSource, &StubTier)> for TypeProvenance {
    fn from((source, tier): (&StubSource, &StubTier)) -> Self {
        match (source, tier) {
            // A custom typeshed keeps Tier-1 trust but its own provenance, so
            // hover can distinguish it from the default Typeshed snapshot
            // ([STUBRES-CUSTOM-TYPESHED]).
            (&StubSource::CustomTypeshed, &StubTier::Tier1) => Self::StubCustomTypeshed,
            (&StubSource::UserStub, &StubTier::Tier1) => Self::StubUser,
            (_, &StubTier::Tier1) => Self::StubTier1,
            (_, &StubTier::Tier2) => Self::StubTier2,
            (_, &StubTier::Tier3) => Self::StubTier3,
        }
    }
}

impl TypeProvenance {
    /// Human-readable label for hover tooltips.
    // Implements [STUBRES-PROVENANCE-HOVER] — the per-provenance suffix shown in
    // LSP hover (e.g. `(typeshed)`, `(best-effort stub, may be inaccurate)`,
    // `(no type stubs available)`); the LSP hover renderer appends it.
    #[must_use]
    pub fn hover_label(self) -> Option<&'static str> {
        match self {
            Self::Source | Self::StubUser => None,
            Self::StubTier1 => Some("(typeshed)"),
            Self::StubCustomTypeshed => Some("(custom typeshed)"),
            Self::StubTier2 => Some("(community stub)"),
            Self::StubTier3 => Some("(best-effort stub, may be inaccurate)"),
            Self::Untyped => Some("(no type stubs available)"),
        }
    }
}

// ---------------------------------------------------------------------------
// Parsed stub types — extracted from `.pyi` files
// ---------------------------------------------------------------------------

/// A single parameter in a stub function signature.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubParam {
    /// Parameter name.
    pub name: String,
    /// Type annotation text (e.g. `"int"`, `"str | None"`).
    pub annotation: Option<String>,
    /// Whether the parameter has a default value.
    pub has_default: bool,
    /// Parameter kind.
    pub kind: StubParamKind,
}

/// How a parameter is passed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StubParamKind {
    /// Normal positional-or-keyword parameter.
    Regular,
    /// `*args` variadic positional.
    Vararg,
    /// `**kwargs` variadic keyword.
    Kwarg,
    /// Keyword-only (appears after `*`).
    KeywordOnly,
    /// Positional-only (appears before `/`).
    PositionalOnly,
}

/// Byte range of a declaration in the immutable stub source that supplied it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StubSpan {
    /// Inclusive byte offset of the declaration name.
    pub start: u32,
    /// Exclusive byte offset of the declaration name.
    pub end: u32,
}

/// A single function signature extracted from a `.pyi` file.
///
/// When `@overload` is used, each overload is a separate `StubFunction`.
/// The overload group is tracked in [`StubModule::overloads`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubFunction {
    /// Function name.
    pub name: String,
    /// Bound `self`/`cls` receiver for methods, including its annotation.
    /// Static methods and module-level functions have no receiver.
    pub receiver: Option<StubParam>,
    /// Call-visible parameters after receiver binding.
    pub params: Vec<StubParam>,
    /// Return type annotation text.
    pub return_type: Option<String>,
    /// Whether this signature is an `@overload` variant.
    pub is_overload: bool,
    /// Whether this is an `async def`.
    pub is_async: bool,
    /// Decorator names (e.g. `"staticmethod"`, `"classmethod"`).
    pub decorators: Vec<String>,
    /// Containing class name, if this is a method.
    pub class_name: Option<String>,
    /// Location of the function name in the exact `.pyi` body.
    pub source_span: StubSpan,
}

/// Render a call-visible stub declaration without its already-bound receiver.
///
/// Parameter kinds and defaults are semantic data, so this renderer preserves
/// positional-only `/`, keyword-only `*`, variadics, annotations, and the
/// declared return type. Hover and signature help use this same declaration
/// object that call checking consumes.
#[must_use]
pub fn render_stub_signature(function: &StubFunction) -> String {
    let mut rendered = format!("def {}(", function.name);
    rendered.push_str(&render_stub_params(&function.params));
    rendered.push(')');
    if let Some(return_type) = &function.return_type {
        rendered.push_str(" -> ");
        rendered.push_str(return_type);
    }
    rendered
}

fn render_stub_params(params: &[StubParam]) -> String {
    let last_positional_only = params
        .iter()
        .rposition(|parameter| parameter.kind == StubParamKind::PositionalOnly);
    let mut parts = Vec::new();
    let mut star_emitted = false;
    for (index, parameter) in params.iter().enumerate() {
        if parameter.kind == StubParamKind::KeywordOnly && !star_emitted {
            parts.push("*".to_owned());
            star_emitted = true;
        }
        let prefix = match parameter.kind {
            StubParamKind::Vararg => "*",
            StubParamKind::Kwarg => "**",
            _ => "",
        };
        let mut part = format!("{prefix}{}", parameter.name);
        if let Some(annotation) = &parameter.annotation {
            part.push_str(": ");
            part.push_str(annotation);
        }
        if parameter.has_default {
            part.push_str(" = ...");
        }
        parts.push(part);
        if parameter.kind == StubParamKind::Vararg {
            star_emitted = true;
        }
        if Some(index) == last_positional_only {
            parts.push("/".to_owned());
        }
    }
    parts.join(", ")
}

/// A class definition extracted from a `.pyi` file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubClass {
    /// Class name.
    pub name: String,
    /// Base class names (text form).
    pub bases: Vec<String>,
    /// Explicit `metaclass=...` expression, kept separate from the base MRO.
    pub metaclass: Option<String>,
    /// Methods defined on this class.
    pub methods: Vec<StubFunction>,
    /// Class-level variable annotations (e.g. `x: int`).
    pub attributes: Vec<StubVariable>,
}

/// A module-level or class-level variable annotation from a `.pyi` file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StubVariable {
    /// Variable name.
    pub name: String,
    /// Type annotation text.
    pub annotation: Option<String>,
}

/// A `from <module> import *` statement in a stub, recorded so re-export
/// following ([STUBRES-PYI-REEXPORTS]) can resolve the target module relative
/// to the stub file and fold its export set into the importer's public API.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StarReexport {
    /// The dotted module path after `from`, without leading dots
    /// (`"tasks"` for `from .tasks import *`; empty for `from . import *`).
    pub module: String,
    /// Relative-import level: number of leading dots (0 = absolute).
    pub level: u32,
}

/// Python/platform evidence used to select guarded declarations in a stub.
///
/// A target is deliberately explicit: callers that have no target evidence use
/// the legacy parser entry points, which retain only declarations valid across
/// every feasible guarded branch ([STUBRES-TYPESHED-VERSION]).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StubTarget {
    /// Concrete target Python `(major, minor)` version.
    pub python_version: (u32, u32),
    /// Concrete target platform or the cross-platform intersection.
    pub platform: StubTargetPlatform,
}

/// Platform evidence for guarded `.pyi` declarations.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum StubTargetPlatform {
    /// Require the declaration/export to be valid on every platform branch.
    All,
    /// Select guards for the exact `sys.platform` value.
    Concrete(String),
}

/// One source contributing names to a `__all__` mutation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DunderAllItem {
    /// A literal string name.
    Name(String),
    /// A referenced module's authoritative `__all__`.
    ModuleAll(StarReexport),
}

/// One ordered mutation of a module's `__all__` list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DunderAllMutation {
    /// `__all__ = value` replaces the prior list.
    Assign(Vec<DunderAllItem>),
    /// `__all__ += value` or `__all__.extend(value)` appends many entries.
    Extend(Vec<DunderAllItem>),
    /// `__all__.append("name")` appends one entry.
    Append(String),
    /// `__all__.remove("name")` removes its first matching entry.
    Remove(String),
}

/// All type information extracted from a single `.pyi` file.
///
/// Designed for efficient lookup by symbol name. Overloaded functions
/// are grouped together — [`overloads`](StubModule::overloads) maps a
/// function name to all its `@overload` variants.
#[derive(Debug, Clone)]
pub struct StubModule {
    /// The dotted module name (e.g. `"os.path"`).
    pub module_name: String,
    /// Filesystem path to the `.pyi` file.
    pub path: PathBuf,
    /// Where this stub came from (user stubs, stub package, typeshed, …).
    pub source: StubSource,
    /// Quality tier of the type information.
    pub tier: StubTier,
    /// Target evidence used to select guarded branches, if supplied.
    pub target: Option<StubTarget>,
    /// Top-level function stubs (non-overloaded or the implementation signature).
    pub functions: HashMap<String, StubFunction>,
    /// Overload groups: function name → ordered list of `@overload` variants.
    pub overloads: HashMap<String, Vec<StubFunction>>,
    /// Class definitions.
    pub classes: HashMap<String, StubClass>,
    /// Module-level variable annotations.
    pub variables: HashMap<String, StubVariable>,
    /// Effective literal `__all__` entries after ordered mutations and guarded
    /// branch intersection. References are resolved by the re-export walker.
    /// `None` when no feasible branch mutates `__all__`.
    pub dunder_all: Option<Vec<String>>,
    /// Ordered `__all__` mutation sequences. Multiple entries are feasible
    /// target branches and are intersected after module references resolve.
    pub dunder_all_variants: Vec<Vec<DunderAllMutation>>,
    /// Names re-exported via the typing spec's redundant-alias convention:
    /// `from y import x as x` / `import x as x` ([STUBRES-PYI-REEXPORTS]).
    pub reexported_names: Vec<String>,
    /// `from <module> import *` statements, whose targets' export sets are
    /// part of this module's public API ([STUBRES-PYI-REEXPORTS]).
    pub star_reexports: Vec<StarReexport>,
}
