//! Tests for [constructors_call_init] from [CHKARCH-DIAG-CATEGORIES]. See docs/specs/CHECKER-ARCHITECTURE-SPEC.md#CHKARCH-DIAG-CATEGORIES
// Integration tests for constructors_call_init: Constructor call errors.

use super::common::*;

#[test]
fn specialized_generic_arg_mismatch() -> Result<(), Box<dyn std::error::Error>> {
    let source = r#"
from typing import TypeVar, Generic
T = TypeVar("T")
class Box(Generic[T]):
    def __init__(self, x: T) -> None:
        self.x = x

Box[int](1.0)
"#;
    let diags = run(source)?;
    let _ = codes(&diags);
    Ok(())
}

#[test]
fn no_custom_init_with_args() -> Result<(), Box<dyn std::error::Error>> {
    let source = r"
class Empty:
    pass

Empty(1, 2, 3)
";
    let diags = run(source)?;
    let _ = codes(&diags);
    Ok(())
}

#[test]
fn valid_constructor_no_diagnostic() -> Result<(), Box<dyn std::error::Error>> {
    let source = r"
class MyClass:
    def __init__(self, x: int) -> None:
        self.x = x

MyClass(42)
";
    let diags = run(source)?;
    assert!(
        !codes(&diags).contains(&"constructors_call_init"),
        "valid constructor call should not fire E0111"
    );
    Ok(())
}

#[test]
fn self_type_incompatibility() -> Result<(), Box<dyn std::error::Error>> {
    let source = r#"
from typing import TypeVar, Generic
T = TypeVar("T")
class Container(Generic[T]):
    def __init__(self, value: T) -> None:
        self.value = value

class SubContainer(Container[int]):
    pass

SubContainer("not an int")
"#;
    let diags = run(source)?;
    let _ = codes(&diags);
    Ok(())
}

#[test]
fn explicit_self_annotation_mismatch() -> Result<(), Box<dyn std::error::Error>> {
    let source = r#"
from typing import TypeVar, Generic
T = TypeVar("T")
class Class4(Generic[T]):
    def __init__(self: "Class4[int]", x: T) -> None:
        pass

Class4[str]()
"#;
    let diags = run(source)?;
    let _ = codes(&diags);
    Ok(())
}

#[test]
fn multiple_init_params() -> Result<(), Box<dyn std::error::Error>> {
    let source = r#"
from typing import TypeVar, Generic
T = TypeVar("T")
class Multi(Generic[T]):
    def __init__(self, x: T, y: T, z: int) -> None:
        pass

Multi[int](1, 2, 3)
Multi[str]("a", "b", 3)
"#;
    let diags = run(source)?;
    let _ = codes(&diags);
    Ok(())
}

#[test]
fn class_with_new_and_init() -> Result<(), Box<dyn std::error::Error>> {
    let source = r"
from typing import Self
class WithNew:
    def __new__(cls) -> Self:
        return super().__new__(cls)
    def __init__(self, x: int) -> None:
        self.x = x

WithNew(42)
";
    let diags = run(source)?;
    let _ = codes(&diags);
    Ok(())
}

#[test]
fn inherited_init() -> Result<(), Box<dyn std::error::Error>> {
    let source = r"
class Base:
    def __init__(self, x: int) -> None:
        self.x = x

class Child(Base):
    pass

Child(42)
";
    let diags = run(source)?;
    let _ = codes(&diags);
    Ok(())
}

/// Regression for issue #44: a class inheriting from an unresolved *external*
/// base (e.g. pydantic v2 `BaseModel`, whose `__init__` is generated by its
/// metaclass) must NOT be reported as "inherits only from `object`". The
/// checker cannot see the base's constructor, so it must stay conservative and
/// not emit constructors_call_init — otherwise every keyword construction of a Pydantic
/// model is a false positive.
#[test]
fn no_false_positive_on_external_base() -> Result<(), Box<dyn std::error::Error>> {
    let source = r#"
from pydantic import BaseModel


class BundleUploadResponse(BaseModel):
    bundle_id: int
    sha256: str


BundleUploadResponse(bundle_id=1, sha256="abc")
"#;
    let diags = run(source)?;
    assert!(
        !codes(&diags).contains(&"constructors_call_init"),
        "constructing a subclass of an unresolved external base must not fire E0111; got: {:?}",
        codes(&diags)
    );
    Ok(())
}
