//! Generates the checker-owned rule catalog from the live `all_rules` registry.

use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug)]
struct CatalogEntry {
    code: String,
    title: String,
    docs_url: String,
}

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed=src/rules");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let rules_dir = manifest_dir.join("src/rules");
    let registry = fs::read_to_string(rules_dir.join("mod.rs"))?;
    let modules = registered_modules(&registry)?;
    let entries = modules
        .iter()
        .map(|module| catalog_entry(&rules_dir, module))
        .collect::<Result<Vec<_>, _>>()?;

    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    fs::write(out_dir.join("rule_catalog_generated.rs"), render(&entries)?)?;
    Ok(())
}

fn registered_modules(registry: &str) -> Result<Vec<String>, String> {
    let function = registry
        .split_once("fn all_rules()")
        .map(|(_, rest)| rest)
        .ok_or_else(|| "rules/mod.rs has no all_rules registry".to_owned())?;
    let list = function
        .split_once("&[")
        .map(|(_, rest)| rest)
        .and_then(|rest| rest.split_once("\n    ]").map(|(body, _)| body))
        .ok_or_else(|| "could not locate all_rules registry body".to_owned())?;

    let modules = list
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix('&')
                .and_then(|entry| entry.strip_suffix(','))
                .and_then(|entry| entry.split_once("::"))
                .map(|(module, _)| module.to_owned())
        })
        .collect::<Vec<_>>();
    if modules.is_empty() {
        Err("all_rules registry contains no rule entries".to_owned())
    } else {
        Ok(modules)
    }
}

fn catalog_entry(rules_dir: &Path, module: &str) -> Result<CatalogEntry, String> {
    let flat = rules_dir.join(format!("{module}.rs"));
    let module_dir = rules_dir.join(module);
    let primary = if flat.is_file() {
        flat
    } else {
        module_dir.join("mod.rs")
    };
    let primary_text = fs::read_to_string(&primary)
        .map_err(|err| format!("failed to read registered rule `{module}`: {err}"))?;
    let (code, title) = extract_header(&primary_text).ok_or_else(|| {
        format!("registered rule `{module}` has no canonical `//! CODE: title` header")
    })?;

    // Rule documentation URLs follow one canonical, code-addressed route.
    // Deriving the URL also covers rules whose shared `ErrorCode` constant
    // lives in a sibling helper module rather than the registered module.
    let docs_url = format!("https://www.basilisk-python.dev/errors/{code}");

    Ok(CatalogEntry {
        code,
        title: clean_sentence(&title),
        docs_url,
    })
}

fn extract_header(text: &str) -> Option<(String, String)> {
    text.lines().find_map(|line| {
        let doc = line.trim().strip_prefix("//! ")?;
        let (raw_code, title) = doc.split_once(':')?;
        let code = raw_code.trim().trim_matches('`');
        // Codes carry no severity class ([CHKARCH-DIAG-CODES]): Basilisk
        // rules are `BSK-nnnn`, conformance rules keep their snake_case names.
        let valid_bsk = code
            .strip_prefix("BSK-")
            .is_some_and(|rest| !rest.is_empty() && rest.bytes().all(|byte| byte.is_ascii_digit()));
        let valid_named = code
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_');
        (valid_bsk || valid_named).then(|| (code.to_owned(), title.trim().to_owned()))
    })
}

fn clean_sentence(value: &str) -> String {
    value.trim().trim_end_matches('.').trim().to_owned()
}

fn render(entries: &[CatalogEntry]) -> Result<String, std::fmt::Error> {
    let mut output = String::from(
        "// @generated by crates/basilisk-checker/build.rs from the live rule registry.\n\
         // Do not edit by hand.\n\n\
         const GENERATED_RULES: &[GeneratedRuleDescriptor] = &[\n",
    );
    for entry in entries {
        output.push_str("    GeneratedRuleDescriptor {\n");
        writeln!(&mut output, "        code: {:?},", entry.code)?;
        writeln!(&mut output, "        title: {:?},", entry.title)?;
        writeln!(&mut output, "        summary: {:?},", entry.title)?;
        writeln!(&mut output, "        docs_url: {:?},", entry.docs_url)?;
        output.push_str("    },\n");
    }
    output.push_str("];\n");
    Ok(output)
}
