[package]
name        = "basilisk-checker"
description = "Type checking rules and diagnostic emission for Basilisk"
version.workspace    = true
edition.workspace    = true
license.workspace    = true

[dependencies]
basilisk-parser.workspace   = true
basilisk-resolver.workspace = true
ruff_python_ast.workspace   = true
ruff_text_size.workspace    = true

[lints]
workspace = true
