[package]
name        = "basilisk-checker"
description = "Type checking rules and diagnostic emission for Basilisk"
version.workspace    = true
edition.workspace    = true
license.workspace    = true

[dependencies]
basilisk-config.workspace   = true
basilisk-parser.workspace   = true
basilisk-resolver.workspace = true
basilisk-stubs.workspace    = true
ruff_python_ast.workspace   = true
ruff_text_size.workspace    = true
basilisk-uv.workspace       = true

[dev-dependencies]
basilisk-test-macros.workspace = true
tempfile = "3"

[lints]
workspace = true
