[package]
name        = "basilisk-compiler"
description = "Basilisk compiler — compiles typed Python to native code"
version.workspace    = true
edition.workspace    = true
license.workspace    = true

[dependencies]
basilisk-parser.workspace   = true
basilisk-resolver.workspace = true
basilisk-checker.workspace  = true
basilisk-stubs.workspace    = true
thiserror.workspace         = true
ruff_python_ast.workspace   = true

[dev-dependencies]
walkdir.workspace = true

[lints]
workspace = true
